Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic 
operations like: 
a) Addition of 2 in all the element  
b) Multiply 3 with all the elements 
c) Divide every element by 2 

In [38]:
import numpy as n
arr=n.array([1,3,5,7])

arr_add=arr+2
print(arr_add)

arr_multi=arr*3
print(arr_multi)

arr_div=arr/2
print(arr_div)

[3 5 7 9]
[ 3  9 15 21]
[0.5 1.5 2.5 3.5]


Q.2 Questions on Basic NumPy Array: 
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 
b) Find the most frequent value and their indice(s) in the following arrays: 
i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [39]:
arr1=n.array([1,2,3,6,4,5])
arr1=arr1[::-1]
print(arr1)

x=n.array([1,2,3,4,5,1,2,1,1,1])
v=n.zeros(5)
for i in x:
    t=i
    v[t-1]=1+v[t-1]
count=-1
f=-1
for i in range(0,5):
    if(count<v[i]):
        count=v[i]
        f=i+1
print(count," ",f)
counter=0
for i in x:
    counter+=1
    if i==f:
        print(counter)

[5 4 6 3 2 1]
5.0   1
1
6
8
9
10


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access 
elements using row and column indices as follows: 
a) Access 1st row, 2nd column  
b) Access 3rd row, 1st column

In [23]:
arr2=n.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr2[0,1])
print(arr2[2,0])

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly 
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, 
shape, total elements, the data type of each element and total number of bytes consumed 
by the array. Find the transpose of this array using reshape() attribute. Can we do the same 
with T attribute? 

In [36]:
Gaurang=n.linspace(10,100,num=25)
print(Gaurang)

print(Gaurang.ndim)

print(Gaurang.dtype)

print(len(Gaurang))

arr_size=Gaurang.size*Gaurang.itemsize
print(arr_size)

print(Gaurang.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
float64
25
200
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> 
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, 
median, max, min, unique elements. Reshape the array to four rows and three columns and 
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three 
columns and name it as resized_ ucs420_<your_name>>

In [44]:
ucs420_Gaurang=n.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(n.mean(ucs420_Gaurang))
print(n.median(ucs420_Gaurang))
print(n.max(ucs420_Gaurang))
print(n.min(ucs420_Gaurang))
print(n.unique(ucs420_Gaurang))
reshaped_ucs420_Gaurang=ucs420_Gaurang.reshape(4,3)
print(reshaped_ucs420_Gaurang)
resized_ucs420_Gaurang=np.resize(reshaped_ucs420_Gaurang,(2,3))
print(resized_ucs420_ruhaan)
     

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
